name: ArchitecturePrototype

options:
  xcodeVersion: 13.2

configs:
  Dev: debug
  Prod: release

options:
  minimumXcodeGenVersion: 2.20
  deploymentTarget:
    iOS: 11.0
  defaultConfig: Dev
  groupSortPosition: top
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1
  configs:
    Dev:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone      
      GCC_OPTIMIZATION_LEVEL: O
      VALIDATE_PRODUCT: NO 
      ONLY_ACTIVE_ARCH: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG                 
    Prod:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -O
      GCC_OPTIMIZATION_LEVEL: s      
      VALIDATE_PRODUCT: YES
      ONLY_ACTIVE_ARCH: NO


targets:
  ArchitecturePrototype:
    type: application
    platform: iOS
    deploymentTarget: 13.0

    sources:
      - path: ArchitecturePrototype

    configFiles:
      Dev: "Configuration/prototype-dev.xcconfig"
      Prod: "Configuration/prototype-prod.xcconfig"

    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CODE_SIGN_ENTITLEMENTS: "ArchitecturePrototype/Resources/Support/ArchitecturePrototype.entitlements"
        CODE_SIGN_STYLE: Manual          
        DEFINES_MODULE: YES
        INFOPLIST_FILE: "ArchitecturePrototype/Resources/Support/Info.plist"
        SWIFT_ENFORCE_EXCLUSIVE_ACCESS: debug-only
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID)                    
        TARGETED_DEVICE_FAMILY: 1
        ENABLE_BITCODE: NO
        XCODEGEN_STATE: YES
        CURRENT_PROJECT_VERSION: 1
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build
                  
      configs:
        Dev:
          CODE_SIGN_IDENTITY: iPhone Developer
          PRODUCT_NAME: Prototype-dev
          MARKETING_VERSION: 1.0            
        Prod:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PRODUCT_NAME: Prototype-prod          

    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework

      - framework: "Carthage/Build/SectionDataSource.xcframework"
      - framework: "Carthage/Build/DifferenceKit.xcframework"
      - framework: "Carthage/Build/Realm.xcframework"
      - framework: "Carthage/Build/RealmSwift.xcframework"  
      - framework: "Carthage/Build/DatabaseObjectsMapper.xcframework"
      - framework: "Carthage/Build/ReactiveSwift.xcframework"
      - framework: "Carthage/Build/ReactiveCocoa.xcframework"

    preBuildScripts:
    postBuildScripts:


  ArchitecturePrototypeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: ArchitecturePrototypeTests
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Manual
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Prototype-dev.app/Prototype-dev
        BUNDLE_LOADER: $(TEST_HOST)

    dependencies:
      - target: ArchitecturePrototype


schemes:
  Prototype-dev:
    build:
      config: Dev
      targets:
        ArchitecturePrototype: run 
    run:
      config: Dev
    test:
      config: Dev
    profile:
      config: Dev
    analyze:
      config: Dev
    archive:
      config: Dev                                         
  Prototype-prod:
    build:
      config: Prod
      targets:
        ArchitecturePrototype: run
    run:
      config: Prod   
    test:
      config: Prod
    profile:
      config: Prod
    analyze:
      config: Prod
    archive:
      config: Prod               
  ArchitecturePrototypeTests:
    build:
      targets:
        ArchitecturePrototypeTests: all
        ArchitecturePrototype: [test]
    test:
      config: Dev
      gatherCoverageData: false
      targets: [ArchitecturePrototypeTests]                                      
